// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'C:/Users/20848/Desktop/Distributed_Database/frontend/ant-design-pro/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import TeamOutlined from 'C:/Users/20848/Desktop/Distributed_Database/frontend/ant-design-pro/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import TableOutlined from 'C:/Users/20848/Desktop/Distributed_Database/frontend/ant-design-pro/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, TeamOutlined, TableOutlined };
